version: "3"
services: 
  app: 
    build: .
    depends_on:
      - db

    ports:
      - "3001:3001"
    networks:
      - appnet
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pingui840
      POSTGRES_DB: app_reservas
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - appnet
networks:
  appnet:

